services:
  db:
    image: postgres:15
    environment: 
      POSTGRES_DB: event_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jayamkavan
    ports:
      - "5432:5432"

  app:
      build: .
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/event_db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: jayamkavan
      depends_on:
        - db