spring.application.name=eventServices
spring.datasource.url=jdbc:postgresql://localhost:5432/event_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
