spring.application.name=discoveryService
spring.datasource.url=jdbc:postgresql://localhost:5432/event_db
spring.datasource.username=postgres
spring.datasource.password=jayamkavan
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true